[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ndg.clap"
description = "A command-line argument parser that builds itself."
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.8"
dependencies = [
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "black>=23.9.1",
    "isort>=5.12.0",
    "mypy>=1.5.1",
]

[project.urls]
Repository = "https://github.com/nicdgonzalez/clap"
"Issue Tracker" = "https://github.com/nicdgonzalez/clap/issues"

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = {attr = "clap.__version__"}

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
